### ISSUE TITLE
Last camera in camera view never displays

### ISSUE THREAD

**Issue by InSearchOfTh1ngs** [AalianKhan/mushroom-strategy#106]
**Describe the bug**
When viewing the cameras in the camera view, the last camera card never displays the camera's feed.  If I update the area of the camera causing it to change it's list position in the camera view it'll start displaying its feed.  This cause another camera to be the last camera card and it will now no longer display it feed.  This issues only pertains to the last camera card in the view.

**Versions**
* Mushroom-Strategy: <del>2.0.0</del> 1.0.1
* HACS: 1.33.0
* Mushroom: <del>3.3.2</del> 3.2.2
* Home Assistant: 2023.11.3

**To Reproduce**

1. Go to camera view
2. Observe that the last camera in the view always displays as blank and not the camera's feed.

**Expected behavior**
The camera view should display all cameras.

**Screenshots**

**Additional context**

**Comment by DigiLive** [comment]
Are you sure about the version?

v2.0.0 isn't released yet.
There's a bug in HACS which shows the readme of the current main branch, instead of the downloaded version.
The downloaded version, is displayed at the top left of our repository page in the HACS integration.
![afbeelding](https://github.com/AalianKhan/mushroom-strategy/assets/7613487/99572493-039b-405e-8c54-f1422502386c)

**Comment by InSearchOfTh1ngs** [comment]
yea sorry.  I'm on the latest stable release then.  the 1.0.1.  I have updated the original issue with that information.

**Comment by DigiLive** [comment]
Unfortunately, I can't reproduce your situation, so I have to ask quite a few more questions.

1. Is there any output in the console, related to our strategy?
2. Do you have any custom configuration for the camera-view or camera-entities?
3. Is it related to a specific area?
   If so, do you have any custom configuration for this area?
4. What happens with multiple cameras in the same area?
5. What happens in an area-view?
6. What happens at another client, E.g., the Companion App or another browser?

Maybe screenshots of the camera- or area-view will help.
Also make sure you've reloaded the cache of your client (browser: CTRL-F5 a few times or Incognito Mode).

**Comment by InSearchOfTh1ngs** [comment]
1. There is nothing in the logs related to the mushroom strategy
2. I have not made any customizations to the camera view.  It is generated purely by the strategy.  The only customization I made was move the  camera view to index 1 (next to the Home view).  Granted this didn't effect it as the issue was present before reordering the views along the top bar.
3. No, the issue follows the very last camera card regardless of the camera entity that is associated with that card.  I have tested this by changing the area of multiple cameras to force one to be the last camera in this view and the issue is consistent with the last camera card regardless of it's associated camera.
4. No area customizations
5. It is always the last camera card that doesn't load the feed.
6. An area view will always load the camera feed.  Granted I don't have any camera cards in any of my area views that happen to be the last card in the view.
7. The issue is consistent with a desktop web browser, and both android and iOS companion apps.

Note: My cameras entities are generated by the Blue Iris custom integration that was installed via HACS.  The integration can be found here: https://github.com/elad-bar/ha-blueiris

Below are some screenshots I took.  Sorry for the strong blur just trying to protect some privacy within my home.
The first photo I have my Living Room camera set associated with my Home-Assistant Living Room area.  You can see that it does not load up a stream
![livingRoomCameraBlank](https://github.com/AalianKhan/mushroom-strategy/assets/30636642/702abef2-eaaf-4ade-befc-3ef3cc2c3717)


In the second photo, I swapped areas of my spare room camera and my living room camera so that the Living room camera is now associated with the spare room area and the spare room camera is associated with the living room area.  The living room area always appears last in the camera view.  Again you can see that the last camera card (Spare room camera) doesn't load its stream
![MovedGuestBedroomCameraToLivingRoom_Blank](https://github.com/AalianKhan/mushroom-strategy/assets/30636642/96f51bf9-16a5-4d95-85f9-f7f97bf0a809)

**Comment by DigiLive** [comment]
> Sorry for the strong blur just trying to protect some privacy within my home.

I completely understand your concerns, but the reason I asked for screenshot, was to determine the layout of the full screen, which you've blurred out as well. As they are now, they're useless to me.
You can blur out only the camera images.

> There is nothing in the logs related to the mushroom strategy.

Also nice to know, but the question was actually to check for output in the JavaScript debug console. In most browser you can open it with <key>F12</key>.
![afbeelding](https://github.com/AalianKhan/mushroom-strategy/assets/7613487/9e978f55-bcf0-4c2c-8d4f-d9c14b1205a8)

**Comment by DigiLive** [comment]
Closed for being stale.
